### ISSUE TITLE
getShowData not listing all available episodes

### ISSUE THREAD

**Issue by hazkiel** [ChrisAlderson/eztv-api-pt#1]
The method getShowData currently only returns a limited set of episodes for a show and this is due to the response when using URLs with the pattern: `https://eztv.ag/shows/<id>/<slug>/`.

However, the search page lists all the episodes of a particular show and would be better suited to for this matter. It has the following URL pattern: `https://eztv.ag/search/?q1=&q2=<id>&search=Search`.

Check the episodes in these URLs to see the difference:
https://eztv.ag/shows/428/the-walking-dead/
https://eztv.ag/search/?q1=&q2=428&search=Search

**Comment by hazkiel** [comment]
I added the functionality and created a pull request.

**Comment by ChrisAlderson** [comment]
Thanks for bringing this to my attention, I never knew they did this.

I've seen your PR, overall it looks good, but there are a couple of small changes I requested.

**Comment by hazkiel** [comment]
Done. Great work on this repo btw, forgot to mention it before... it came in handy in one of my projects.

**Comment by ChrisAlderson** [comment]
Merged PR #2
